services:
  - type: web
    name: ao3-history-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
